title: Bye Bye Mr. Cohen
author: Priyal Garg
email: priyalgarg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Priyal Garg is creating this website so that she can pass her AP Computer Science A class.

# social links
github_username:  Priyal-bit

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
